kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
- name: docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: lbischof/tgtg-notifier
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
